language: generic
install: ./build.sh
script: ./test.sh
env:
  - NGINX_V=1.11.4 OPENRESTY_V=1.11.2.5
  - NGINX_V=1.11.5 OPENRESTY_V=1.11.2.5
  - NGINX_V=1.12.0 OPENRESTY_V=1.11.2.5
  - NGINX_V=1.12.1 OPENRESTY_V=1.11.2.5
  - NGINX_V=1.13.5 OPENRESTY_V=1.11.2.5
